Linked calculation file with discord somewhat
DarkWolf2244/HackersEncyclopediaBot pull request #6
Opened 2021-02-18 10:22 UTC by Amethysm

2021-02-18 11:12 UTC, DarkWolf2244 requested changes
Can we please remove the pycache files? It's unnecessary to have logs and pycache stuff.

2021-02-18 13:39 UTC, DarkWolf2244 approved these changes

2021-02-20 07:22 UTC, DaRealCodeWritten commented
Technically we could disable pycaches but that would actually slow the bot down a little bit

2021-02-20 07:22 UTC, DaRealCodeWritten approved these changes

2021-02-20 07:22 UTC, merged